name: desafio_tecnico
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_lints: ^3.0.1
  url_launcher: ^6.2.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  mobx: ^2.2.3
  flutter_mobx: ^2.2.0+1
  json_annotation: ^4.8.1
  mobx_codegen: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1


flutter:

  uses-material-design: true
